USE employeemanagementsystem;

DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE IF NOT EXISTS DEPARTMENT (
    DEPT_ID BIGINT NOT NULL AUTO_INCREMENT,
    DEPT_NAME varchar(255) NOT NULL,
    PRIMARY KEY (DEPT_ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    EMPLOYEE_ID BIGINT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_NAME VARCHAR(255) NOT NULL,
	EMPLOYEE_EMAIL VARCHAR(255) NOT NULL,
    EMPLOYEE_PHONE BIGINT NOT NULL,
    EMPLOYEE_ADDRESS VARCHAR(255) NOT NULL,
    EMPLOYEE_DOB DATE NOT NULL,
    DEPT_ID BIGINT NOT NULL,
    MANAGER_ID BIGINT,
   
   PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT FK_DEPT_ID FOREIGN KEY (DEPT_ID)
        REFERENCES DEPARTMENT(DEPT_ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_MANAGER_ID FOREIGN KEY (MANAGER_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID)
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

DROP TABLE IF EXISTS GOVERNMENT_HOLIDAY;
CREATE TABLE IF NOT EXISTS GOVERNMENT_HOLIDAY (
    HOLIDAY_ID BIGINT NOT NULL AUTO_INCREMENT,
    HOLIDAY_NAME TEXT NOT NULL,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE NOT NULL,
    PRIMARY KEY (HOLIDAY_ID),
    CONSTRAINT DATE_CHECK CHECK (FROM_DATE <= TO_DATE)
) ENGINE=InnoDB;

DROP TABLE IF EXISTS LEAVE_TYPE;
CREATE TABLE IF NOT EXISTS LEAVE_TYPE (
    LEAVE_TYPE_ID SMALLINT NOT NULL AUTO_INCREMENT,
	LEAVE_TYPE_NAME TEXT NOT NULL,
    PRIMARY KEY (LEAVE_TYPE_ID)
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS LEAVES(
    EMP_ID BIGINT NOT NULL,
    LEAVE_TYPE_ID SMALLINT NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    APPROVAL_STATUS BOOLEAN,
    APPROVAL_BY BIGINT,
    CONSTRAINT fk_approval_by FOREIGN KEY (APPROVAL_BY)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_emp_id FOREIGN KEY (EMP_ID)
        REFERENCES EMPLOYEE (EMPLOYEE_ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_leave_type_id FOREIGN KEY (LEAVE_TYPE_ID)
        REFERENCES LEAVE_TYPE (LEAVE_TYPE_ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT DATE_CHECK_LEAVES CHECK (END_DATE >= START_DATE)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS HR (
    EMPLOYEE_ID BIGINT NOT NULL,
    HR_ID BIGINT NOT NULL AUTO_INCREMENT,
    
    PRIMARY KEY (HR_ID),
    CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(EMPLOYEE_ID)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
) ENGINE=InnoDB;
